/**
 * Accessibility test template auto-generated by the react-native-accessibility skill.
 *
 * Uses @testing-library/react-native to verify accessibility properties
 * on rendered components.
 *
 * Setup:
 * 1. Install dependencies:
 *    npm install --save-dev @testing-library/react-native @testing-library/jest-native
 * 2. Add to jest.config.js:
 *    setupFilesAfterSetup: ['@testing-library/jest-native/extend-expect']
 * 3. Replace <AppName> and component imports with your actual components
 * 4. Run with: npx jest accessibility.test.tsx
 */

import React from 'react';
import { render, screen } from '@testing-library/react-native';

// TODO: Replace with your actual component imports
// import { HomeScreen } from '../screens/HomeScreen';
// import { SettingsScreen } from '../screens/SettingsScreen';

// MARK: - Helpers

/**
 * Verify that an element has the required accessibility properties.
 */
function expectAccessible(
  element: ReturnType<typeof screen.getByTestId>,
  expectations: {
    label?: string | RegExp;
    hint?: string | RegExp;
    role?: string;
    state?: Record<string, unknown>;
  },
) {
  if (expectations.label) {
    expect(element).toHaveAccessibleName(expectations.label);
  }
  if (expectations.hint) {
    expect(element.props.accessibilityHint).toMatch(expectations.hint);
  }
  if (expectations.role) {
    expect(element.props.accessibilityRole).toBe(expectations.role);
  }
  if (expectations.state) {
    expect(element.props.accessibilityState).toMatchObject(expectations.state);
  }
}

/**
 * Verify that all images in the tree have accessibility labels or are hidden.
 */
function expectAllImagesAccessible(container: ReturnType<typeof render>) {
  const images = container.UNSAFE_queryAllByType(
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    require('react-native').Image,
  );
  images.forEach((image) => {
    const props = image.props;
    const hasLabel = !!props.accessibilityLabel;
    const isHidden =
      props.accessible === false ||
      props.accessibilityElementsHidden === true ||
      props.importantForAccessibility === 'no' ||
      props.importantForAccessibility === 'no-hide-descendants';
    expect(hasLabel || isHidden).toBe(true);
  });
}

/**
 * Verify that all pressable elements have labels and roles.
 */
function expectAllPressablesLabeled(container: ReturnType<typeof render>) {
  const pressables = container.getAllByRole('button');
  pressables.forEach((pressable) => {
    expect(pressable.props.accessibilityLabel || pressable.props.children).toBeTruthy();
  });
}

// MARK: - Screen Tests
//
// Add one describe block per screen/component. Each test should:
// 1. Render the component with required providers
// 2. Verify accessibility properties on key elements
//
// Example:
//
// describe('HomeScreen Accessibility', () => {
//   it('renders with accessible elements', () => {
//     const result = render(<HomeScreen />);
//
//     // All images have labels or are hidden
//     expectAllImagesAccessible(result);
//
//     // All buttons have labels
//     expectAllPressablesLabeled(result);
//   });
//
//   it('has accessible navigation buttons', () => {
//     render(<HomeScreen />);
//
//     const settingsButton = screen.getByLabelText('Settings');
//     expectAccessible(settingsButton, {
//       role: 'button',
//       hint: /opens.*settings/i,
//     });
//   });
//
//   it('has accessible form inputs', () => {
//     render(<HomeScreen />);
//
//     const searchInput = screen.getByLabelText('Search');
//     expect(searchInput.props.accessibilityRole).toBe('search');
//   });
//
//   it('marks section headers correctly', () => {
//     render(<HomeScreen />);
//
//     const header = screen.getByText('Recent Orders');
//     expect(header.props.accessibilityRole).toBe('header');
//   });
//
//   it('hides decorative elements', () => {
//     const result = render(<HomeScreen />);
//     expectAllImagesAccessible(result);
//   });
// });

// MARK: - Generated Tests
// The skill will insert test blocks below this line.
// ---GENERATED-TESTS-START---

describe('Accessibility Audit', () => {
  it('placeholder — replace with actual screen tests', () => {
    // TODO: Render your main screen and run accessibility checks
    expect(true).toBe(true);
  });
});

// ---GENERATED-TESTS-END---

// MARK: - Touch Target Tests
//
// Use this pattern to verify touch target sizes meet 48x48 minimum:
//
// it('has adequate touch targets', () => {
//   const { getByRole } = render(<MyComponent />);
//   const button = getByRole('button', { name: 'Close' });
//   const { width, height } = button.props.style;
//   const hitSlop = button.props.hitSlop || { top: 0, bottom: 0, left: 0, right: 0 };
//   const totalWidth = (width || 48) + (hitSlop.left || 0) + (hitSlop.right || 0);
//   const totalHeight = (height || 48) + (hitSlop.top || 0) + (hitSlop.bottom || 0);
//   expect(totalWidth).toBeGreaterThanOrEqual(48);
//   expect(totalHeight).toBeGreaterThanOrEqual(48);
// });
