import XCTest

/// Accessibility audit tests auto-generated by the swift-accessibility skill.
///
/// These tests use the `performAccessibilityAudit()` API (Xcode 15+ / iOS 17+)
/// to catch common accessibility issues at the UI-test level.
///
/// Usage:
/// 1. Replace `<AppName>` with your app's module name
/// 2. Fill in navigation steps to reach each screen
/// 3. Run with `xcodebuild test` or Xcode's Test navigator
///
/// Audit categories checked:
/// - `.dynamicType` — text scales with Dynamic Type
/// - `.contrast` — foreground/background contrast meets WCAG AA
/// - `.sufficientElementDescription` — elements have meaningful labels
/// - `.elementDetection` — interactive elements are accessible
/// - `.hitRegion` — touch targets meet 44x44pt minimum

final class AccessibilityAuditTests: XCTestCase {

    let app = XCUIApplication()

    override func setUpWithError() throws {
        continueAfterFailure = false
        app.launch()
    }

    // MARK: - Audit Helpers

    /// Run a full accessibility audit on the current screen.
    ///
    /// - Parameter screenName: A human-readable name for the screen (used in failure messages)
    /// - Parameter issueFilter: Optional filter to suppress known acceptable warnings
    @MainActor
    private func auditCurrentScreen(
        named screenName: String,
        issueFilter: ((XCUIAccessibilityAuditIssue) -> Bool)? = nil
    ) throws {
        let auditTypes: XCUIAccessibilityAuditType = [
            .contrast,
            .dynamicType,
            .elementDetection,
            .hitRegion,
            .sufficientElementDescription
        ]

        if let filter = issueFilter {
            try app.performAccessibilityAudit(for: auditTypes) { issue in
                filter(issue)
            }
        } else {
            try app.performAccessibilityAudit(for: auditTypes)
        }
    }

    // MARK: - Screen Audits
    //
    // Add one test method per screen/view. Each method should:
    // 1. Navigate to the screen
    // 2. Call auditCurrentScreen(named:)
    //
    // Example:
    //
    // @MainActor
    // func testHomeScreenAccessibility() throws {
    //     // The app launches to the home screen by default
    //     try auditCurrentScreen(named: "Home")
    // }
    //
    // @MainActor
    // func testSettingsScreenAccessibility() throws {
    //     app.buttons["settingsButton"].tap()
    //     try auditCurrentScreen(named: "Settings")
    // }
    //
    // @MainActor
    // func testProfileScreenAccessibility() throws {
    //     app.tabBars.buttons["Profile"].tap()
    //     try auditCurrentScreen(named: "Profile")
    // }

    // MARK: - Generated Tests
    // The skill will insert test methods below this line.
    // ---GENERATED-TESTS-START---

    @MainActor
    func testMainScreenAccessibility() throws {
        // TODO: Add navigation to the main screen if needed
        try auditCurrentScreen(named: "Main Screen")
    }

    // ---GENERATED-TESTS-END---

    // MARK: - Issue Filters
    //
    // Use filters to suppress known acceptable audit warnings.
    //
    // Example: Suppress contrast warnings on a specific decorative element
    //
    // private func filterKnownIssues(_ issue: XCUIAccessibilityAuditIssue) -> Bool {
    //     // Return true to suppress the issue, false to keep it
    //     if issue.auditType == .contrast,
    //        issue.element?.identifier == "decorativeBackground" {
    //         return true
    //     }
    //     return false
    // }
}
